### PR TITLE
[064][FE] Integrate creating University in landing page

### PR DESCRIPTION
**Pull request by JohnRoyCabezas**
## Asana Link

https://app.asana.com/0/1203011106874563/1203204651447824
https://app.asana.com/0/1203011106874563/1203204651447827
https://app.asana.com/0/1203011106874563/1203204651447826

## Pre-requisite

- [ ] npm i
- [ ] php artisan migrate

## Commands

- [ ] in the terminal, go to the project directory and cd into api directory - `cd api`
- [ ] run `php artisan migrate`

- [ ] in the terminal, go to the project directory and cd into client directory - `cd client`
- [ ] run `npm start`

## Expected Output
 
- [ ] New users can register a brand-new university as well as register their admin account.

## Screenshots

image
image
image
image
image

### CODE REVIEW

**Comment by arden-dave** [comment]
- I think it's better if after clicking `Create University` button, the user will be redirected back to login page or automatically logged in.
- Also the password input field should be of type `password`

**Comment by JohnRoyCabezas** [comment]
> * I think it's better if after clicking `Create University` button, the user will be redirected back to login page or automatically logged in.
> * Also the password input field should be of type `password`

Will

> * I think it's better if after clicking `Create University` button, the user will be redirected back to login page or automatically logged in.
> * Also the password input field should be of type `password`

Oh I forgot to change the password input field. I'll update it. Regarding `after clicking the university button` I'll ask the client if they want to be redirected to the login page or if we auto login.

**Review by jasonchuacodes — COMMENTED** [review]
- [ ] errors not showing if form values are incorrect during registration (i.e. password/confirmation not matching)
- [ ] page redirect after successful university registration
- [ ] success modal not showing upon successful registration
  - [ ] redirect the OK button of success modal to login page (to login) or admin announcement page (if auto login after registration)

optional:
- [ ] back button

**Comment by arden-dave** [comment]
image

- Errors should be handled (e.g existing university name and admin email). There are no error indicators.

**Pull request merged**
